# Generated by Django 2.2 on 2021-08-08 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NginxConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='站点名称')),
                ('content', models.TextField(blank=True, max_length=2000000, null=True, verbose_name='ng配置')),
                ('comments', models.CharField(blank=True, default='', max_length=256, verbose_name='备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('status', models.CharField(choices=[('running', '启用'), ('closed', '关闭')], default='running', max_length=16, verbose_name='使用状态')),
                ('appid', models.CharField(blank=True, max_length=32, null=True, verbose_name='站点APPID')),
                ('dep_owner', models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='开发负责人')),
                ('ops_owner', models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='运维负责人')),
                ('qa_owner', models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='测试负责人')),
                ('l1_biz', models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='一级业务')),
                ('parent', models.CharField(blank=True, default='unknown', max_length=128, null=True, verbose_name='二级业务')),
                ('conf_add_status', models.BooleanField(default=False, verbose_name='consul类型，首次生产data文件')),
            ],
            options={
                'verbose_name': 'Nginx配置',
                'verbose_name_plural': 'Nginx配置',
            },
        ),
        migrations.CreateModel(
            name='NginxModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ng名称')),
                ('desc', models.CharField(blank=True, default='', max_length=128, verbose_name='ng描述')),
                ('managerIp', models.GenericIPAddressField(verbose_name='远程调用IP')),
                ('confPath', models.CharField(max_length=512, verbose_name='ng配置路径')),
                ('rmCmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='删除命令')),
                ('syncCmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='同步命令')),
                ('dumpCmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='dump文件命令')),
                ('reloadCmd', models.CharField(blank=True, max_length=512, null=True, verbose_name='reload命令')),
                ('upstream_status_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='upstream_status_url')),
                ('upstream_show_url', models.CharField(blank=True, max_length=512, null=True, verbose_name='upstream_show_url')),
                ('consulApi', models.CharField(blank=True, max_length=512, null=True, verbose_name='consulApi')),
                ('template', models.TextField(blank=True, default='', verbose_name='站点模板')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('region', models.CharField(max_length=64, verbose_name='所属机房')),
                ('status', models.CharField(choices=[('running', '启用'), ('closed', '关闭')], default='running', max_length=16, verbose_name='使用状态')),
                ('nginx_type', models.CharField(choices=[('consul', 'consul'), ('default', 'default')], default='default', max_length=16, verbose_name='nginx类型')),
                ('group_ops', models.CharField(blank=True, max_length=64, null=True, verbose_name='OPS操作组')),
            ],
            options={
                'verbose_name': 'Nginx管理',
                'verbose_name_plural': 'Nginx管理',
                'unique_together': {('name', 'region')},
            },
        ),
        migrations.CreateModel(
            name='NginxInstanceOps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_name', models.CharField(choices=[('sync', 'sync'), ('reload', 'reload'), ('remove', 'remove')], default='sync', max_length=16, verbose_name='操作名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('ops_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('operator', models.CharField(default='unknown', max_length=64, null=True, verbose_name='操作人')),
                ('ops_status', models.CharField(choices=[('running', '运行中'), ('success', '执行成功'), ('failed', '执行失败')], default='running', max_length=32, verbose_name='操作状态')),
                ('ops_2_conf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nginx.NginxConf', verbose_name='关联nginx配置')),
            ],
            options={
                'verbose_name_plural': 'Nginx操作表',
            },
        ),
        migrations.AddField(
            model_name='nginxconf',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nginx.NginxModel', verbose_name='关联ng模块'),
        ),
        migrations.CreateModel(
            name='NginxAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('SetConf', '生成配置'), ('dump_path', '生成dump文件'), ('sync', '同步操作'), ('reload', '重载操作'), ('dns_check', '域名验证'), ('es_check', '访问日志验证'), ('rm_conf', '移除配置文件')], max_length=64, verbose_name='动作')),
                ('msg', models.TextField(max_length=40960, verbose_name='操作信息')),
                ('operator', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作人')),
                ('action_status', models.CharField(choices=[('running', '运行中'), ('success', '执行成功'), ('failed', '执行失败')], default='running', max_length=16, verbose_name='执行状态')),
                ('ops_date', models.DateTimeField(auto_now=True, verbose_name='操作时间')),
                ('action_2_ops', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nginx.NginxInstanceOps', verbose_name='管理ops表')),
            ],
            options={
                'verbose_name_plural': 'NginxAction详情表',
            },
        ),
        migrations.AlterUniqueTogether(
            name='nginxconf',
            unique_together={('name', 'type')},
        ),
    ]
