# Generated by Django 2.2 on 2021-08-08 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nginx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nginxconf',
            name='action_ops',
            field=models.CharField(choices=[('running', '运行中'), ('success', '成功'), ('failed', '执行失败')], default='success', max_length=16, verbose_name='发布action运行状态'),
        ),
    ]
