# Generated by Django 2.2 on 2021-08-14 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='dec',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='权限描述'),
        ),
    ]
