# Generated by Django 2.2 on 2021-08-14 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='menus',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
