# Generated by Django 2.2 on 2021-08-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_permission_dec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permission',
            name='dec',
        ),
    ]
