# Generated by Django 2.2 on 2021-08-10 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='path',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='请求路径正则'),
        ),
        migrations.AddField(
            model_name='permission',
            name='sign',
            field=models.CharField(default='admin', max_length=30, verbose_name='权限标识'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='permission',
            name='method',
            field=models.CharField(blank=True, choices=[('POST', '增'), ('DELETE', '删'), ('PUT', '改'), ('PATCH', '局部改'), ('GET', '查')], default='', max_length=8, verbose_name='方法'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Permission', verbose_name='父权限'),
        ),
    ]
